name: Deploy FastAPI app to EKS
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.24.0' # default is latest stable
      id: install

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Get ECR registry
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mark-password: 'false'

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: testdeploy
        IMAGE_TAG: 1.1
      run: |
        docker build -t 590184058011.dkr.ecr.ap-southeast-2.amazonaws.com/testdeploy:$IMAGE_TAG -f service1/Dockerfile service1
        docker push 590184058011.dkr.ecr.ap-southeast-2.amazonaws.com/testdeploy:$IMAGE_TAG

    - name: Update kube config
      run: aws eks update-kubeconfig --name testdeploy
    
    - name: Deploy to EKS
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        